version: "3"

services:

    app:
        image: webdevops/php-apache-dev:8.1
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: app
            DB_USERNAME: root
            DB_PASSWORD: password
        links:
            - db:db
        ports:
            - "8000:80"
        volumes:
            - .:/app
            - ./setup.sh:/opt/docker/provision/entrypoint.d/99-setup.sh

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
        volumes:
            - /var/lib/mysql
